export const images = [
  [
    "https://srkrec.edu.in/img/slides/new/1.jpg",
    "https://srkrec.edu.in/img/slides/new/2.jpg",
    "https://srkrec.edu.in/img/slides/new/3.jpg",
    "https://srkrec.edu.in/img/slides/new/4.jpg",
    "https://srkrec.edu.in/img/slides/new/5.jpg",
  ],
  [
    "https://srkrec.edu.in/img/slides/new/11.jpg",
    "https://srkrec.edu.in/img/slides/new/12.jpg",
    "https://srkrec.edu.in/img/slides/new/13.jpg",
    "https://srkrec.edu.in/img/slides/new/14.jpg",
    "https://srkrec.edu.in/img/slides/new/15.jpg",
    "https://srkrec.edu.in/img/slides/new/16.jpg",
    "https://srkrec.edu.in/img/slides/new/17.jpg",
    "https://srkrec.edu.in/img/slides/new/18.jpg",
  ],
  [
    "https://srkrec.edu.in/img/slides/new/21.jpg",
    "https://srkrec.edu.in/img/slides/new/22.jpg",
    "https://srkrec.edu.in/img/slides/new/23.jpg",
    "https://srkrec.edu.in/img/slides/new/24.jpg",
    "https://srkrec.edu.in/img/slides/new/25.jpg",
    "https://srkrec.edu.in/img/slides/new/26.jpg",
    "https://srkrec.edu.in/img/slides/new/27.jpg",
    "https://srkrec.edu.in/img/slides/new/28.jpg",
    "https://srkrec.edu.in/img/slides/new/29.jpg",
    
  ],
];
